### ISSUE TITLE
Sensitive Data

### ISSUE THREAD

**Issue by DanielFelizardoDev** [community-bank/backend#13]
# Warning

The link data for the database open? This can be a problem, refactor this code so that the company does not suffer damage causes for lack of security.

## File
.env.default

**Comment by romulo94** [comment]
@DanielFelizardoDev  
Thanks. But it's not a real project yet. The main objective is learning. And in the file there is not exists any secret key, cause everything is running in localhost.
But thanks for the alert. We will be careful about sensitive data

**Comment by DanielFelizardoDev** [comment]
You' re welcome! I expect whatever productive, I'm here to help you.

**Comment by jackoliveira** [comment]
> # Warning
> The link data for the database open? This can be a problem, refactor this code so that the company does not suffer damage causes for lack of security.
> 
> ## File
> .env.default

Thanks for the reply @DanielFelizardoDev , as @romulo94 said, the idea is to use this file with this configuration only in Development mode, all the sensitive data will be carefully planned during the project.
